/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AgentRegistry {
  export type AgentConfigStruct = {
    owner: AddressLike;
    dailyBudget: BigNumberish;
    perTxLimit: BigNumberish;
    todaySpent: BigNumberish;
    lastResetTimestamp: BigNumberish;
    active: boolean;
  };

  export type AgentConfigStructOutput = [
    owner: string,
    dailyBudget: bigint,
    perTxLimit: bigint,
    todaySpent: bigint,
    lastResetTimestamp: bigint,
    active: boolean
  ] & {
    owner: string;
    dailyBudget: bigint;
    perTxLimit: bigint;
    todaySpent: bigint;
    lastResetTimestamp: bigint;
    active: boolean;
  };
}

export interface AgentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addToBlacklist"
      | "addToWhitelist"
      | "agentBalances"
      | "agents"
      | "blacklist"
      | "blacklistArray"
      | "deactivateAgent"
      | "depositFunds"
      | "depositFundsNative"
      | "executePayment"
      | "getAgentBalance"
      | "getAgentConfig"
      | "getBlacklist"
      | "getRemainingDailyBudget"
      | "getWhitelist"
      | "isBlacklisted"
      | "isWhitelisted"
      | "reactivateAgent"
      | "registerAgent"
      | "removeFromBlacklist"
      | "removeFromWhitelist"
      | "updateAgent"
      | "usdc"
      | "whitelist"
      | "whitelistArray"
      | "withdrawFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddedToBlacklist"
      | "AddedToWhitelist"
      | "AgentDeactivated"
      | "AgentReactivated"
      | "AgentRegistered"
      | "AgentUpdated"
      | "BudgetReset"
      | "FundsDeposited"
      | "FundsWithdrawn"
      | "PaymentBlocked"
      | "PaymentExecuted"
      | "RemovedFromBlacklist"
      | "RemovedFromWhitelist"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addToBlacklist",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addToWhitelist",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "agentBalances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "agents", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "blacklist",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistArray",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositFunds",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositFundsNative",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executePayment",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentConfig",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBlacklist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingDailyBudget",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWhitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isBlacklisted",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isWhitelisted",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reactivateAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeFromBlacklist",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeFromWhitelist",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAgent",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "whitelist",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistArray",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addToBlacklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addToWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "blacklist", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "blacklistArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositFundsNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBlacklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingDailyBudget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBlacklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reactivateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeFromBlacklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeFromWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "whitelist", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "whitelistArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;
}

export namespace AddedToBlacklistEvent {
  export type InputTuple = [agent: AddressLike, addr: AddressLike];
  export type OutputTuple = [agent: string, addr: string];
  export interface OutputObject {
    agent: string;
    addr: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AddedToWhitelistEvent {
  export type InputTuple = [agent: AddressLike, addr: AddressLike];
  export type OutputTuple = [agent: string, addr: string];
  export interface OutputObject {
    agent: string;
    addr: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentDeactivatedEvent {
  export type InputTuple = [agent: AddressLike];
  export type OutputTuple = [agent: string];
  export interface OutputObject {
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentReactivatedEvent {
  export type InputTuple = [agent: AddressLike];
  export type OutputTuple = [agent: string];
  export interface OutputObject {
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agent: AddressLike,
    owner: AddressLike,
    dailyBudget: BigNumberish,
    perTxLimit: BigNumberish
  ];
  export type OutputTuple = [
    agent: string,
    owner: string,
    dailyBudget: bigint,
    perTxLimit: bigint
  ];
  export interface OutputObject {
    agent: string;
    owner: string;
    dailyBudget: bigint;
    perTxLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentUpdatedEvent {
  export type InputTuple = [
    agent: AddressLike,
    newDailyBudget: BigNumberish,
    newPerTxLimit: BigNumberish
  ];
  export type OutputTuple = [
    agent: string,
    newDailyBudget: bigint,
    newPerTxLimit: bigint
  ];
  export interface OutputObject {
    agent: string;
    newDailyBudget: bigint;
    newPerTxLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BudgetResetEvent {
  export type InputTuple = [agent: AddressLike, previousSpent: BigNumberish];
  export type OutputTuple = [agent: string, previousSpent: bigint];
  export interface OutputObject {
    agent: string;
    previousSpent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsDepositedEvent {
  export type InputTuple = [agent: AddressLike, amount: BigNumberish];
  export type OutputTuple = [agent: string, amount: bigint];
  export interface OutputObject {
    agent: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsWithdrawnEvent {
  export type InputTuple = [agent: AddressLike, amount: BigNumberish];
  export type OutputTuple = [agent: string, amount: bigint];
  export interface OutputObject {
    agent: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentBlockedEvent {
  export type InputTuple = [
    agent: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    agent: string,
    recipient: string,
    amount: bigint,
    reason: string
  ];
  export interface OutputObject {
    agent: string;
    recipient: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentExecutedEvent {
  export type InputTuple = [
    agent: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish,
    memo: string
  ];
  export type OutputTuple = [
    agent: string,
    recipient: string,
    amount: bigint,
    memo: string
  ];
  export interface OutputObject {
    agent: string;
    recipient: string;
    amount: bigint;
    memo: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemovedFromBlacklistEvent {
  export type InputTuple = [agent: AddressLike, addr: AddressLike];
  export type OutputTuple = [agent: string, addr: string];
  export interface OutputObject {
    agent: string;
    addr: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemovedFromWhitelistEvent {
  export type InputTuple = [agent: AddressLike, addr: AddressLike];
  export type OutputTuple = [agent: string, addr: string];
  export interface OutputObject {
    agent: string;
    addr: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgentRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addToBlacklist: TypedContractMethod<
    [agent: AddressLike, addr: AddressLike],
    [void],
    "nonpayable"
  >;

  addToWhitelist: TypedContractMethod<
    [agent: AddressLike, addr: AddressLike],
    [void],
    "nonpayable"
  >;

  agentBalances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  agents: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        owner: string;
        dailyBudget: bigint;
        perTxLimit: bigint;
        todaySpent: bigint;
        lastResetTimestamp: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  blacklist: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  blacklistArray: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  deactivateAgent: TypedContractMethod<
    [agent: AddressLike],
    [void],
    "nonpayable"
  >;

  depositFunds: TypedContractMethod<
    [agent: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  depositFundsNative: TypedContractMethod<
    [agent: AddressLike],
    [void],
    "payable"
  >;

  executePayment: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish, memo: string],
    [void],
    "nonpayable"
  >;

  getAgentBalance: TypedContractMethod<[agent: AddressLike], [bigint], "view">;

  getAgentConfig: TypedContractMethod<
    [agent: AddressLike],
    [AgentRegistry.AgentConfigStructOutput],
    "view"
  >;

  getBlacklist: TypedContractMethod<[agent: AddressLike], [string[]], "view">;

  getRemainingDailyBudget: TypedContractMethod<
    [agent: AddressLike],
    [bigint],
    "view"
  >;

  getWhitelist: TypedContractMethod<[agent: AddressLike], [string[]], "view">;

  isBlacklisted: TypedContractMethod<
    [agent: AddressLike, addr: AddressLike],
    [boolean],
    "view"
  >;

  isWhitelisted: TypedContractMethod<
    [agent: AddressLike, addr: AddressLike],
    [boolean],
    "view"
  >;

  reactivateAgent: TypedContractMethod<
    [agent: AddressLike],
    [void],
    "nonpayable"
  >;

  registerAgent: TypedContractMethod<
    [agent: AddressLike, dailyBudget: BigNumberish, perTxLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  removeFromBlacklist: TypedContractMethod<
    [agent: AddressLike, addr: AddressLike],
    [void],
    "nonpayable"
  >;

  removeFromWhitelist: TypedContractMethod<
    [agent: AddressLike, addr: AddressLike],
    [void],
    "nonpayable"
  >;

  updateAgent: TypedContractMethod<
    [
      agent: AddressLike,
      newDailyBudget: BigNumberish,
      newPerTxLimit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  whitelist: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  whitelistArray: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  withdrawFunds: TypedContractMethod<
    [agent: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addToBlacklist"
  ): TypedContractMethod<
    [agent: AddressLike, addr: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addToWhitelist"
  ): TypedContractMethod<
    [agent: AddressLike, addr: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "agentBalances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        owner: string;
        dailyBudget: bigint;
        perTxLimit: bigint;
        todaySpent: bigint;
        lastResetTimestamp: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "blacklist"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "blacklistArray"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "deactivateAgent"
  ): TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositFunds"
  ): TypedContractMethod<
    [agent: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositFundsNative"
  ): TypedContractMethod<[agent: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "executePayment"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish, memo: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAgentBalance"
  ): TypedContractMethod<[agent: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAgentConfig"
  ): TypedContractMethod<
    [agent: AddressLike],
    [AgentRegistry.AgentConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBlacklist"
  ): TypedContractMethod<[agent: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRemainingDailyBudget"
  ): TypedContractMethod<[agent: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getWhitelist"
  ): TypedContractMethod<[agent: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "isBlacklisted"
  ): TypedContractMethod<
    [agent: AddressLike, addr: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isWhitelisted"
  ): TypedContractMethod<
    [agent: AddressLike, addr: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "reactivateAgent"
  ): TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [agent: AddressLike, dailyBudget: BigNumberish, perTxLimit: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeFromBlacklist"
  ): TypedContractMethod<
    [agent: AddressLike, addr: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeFromWhitelist"
  ): TypedContractMethod<
    [agent: AddressLike, addr: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateAgent"
  ): TypedContractMethod<
    [
      agent: AddressLike,
      newDailyBudget: BigNumberish,
      newPerTxLimit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "whitelist"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "whitelistArray"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawFunds"
  ): TypedContractMethod<
    [agent: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AddedToBlacklist"
  ): TypedContractEvent<
    AddedToBlacklistEvent.InputTuple,
    AddedToBlacklistEvent.OutputTuple,
    AddedToBlacklistEvent.OutputObject
  >;
  getEvent(
    key: "AddedToWhitelist"
  ): TypedContractEvent<
    AddedToWhitelistEvent.InputTuple,
    AddedToWhitelistEvent.OutputTuple,
    AddedToWhitelistEvent.OutputObject
  >;
  getEvent(
    key: "AgentDeactivated"
  ): TypedContractEvent<
    AgentDeactivatedEvent.InputTuple,
    AgentDeactivatedEvent.OutputTuple,
    AgentDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentReactivated"
  ): TypedContractEvent<
    AgentReactivatedEvent.InputTuple,
    AgentReactivatedEvent.OutputTuple,
    AgentReactivatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentUpdated"
  ): TypedContractEvent<
    AgentUpdatedEvent.InputTuple,
    AgentUpdatedEvent.OutputTuple,
    AgentUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "BudgetReset"
  ): TypedContractEvent<
    BudgetResetEvent.InputTuple,
    BudgetResetEvent.OutputTuple,
    BudgetResetEvent.OutputObject
  >;
  getEvent(
    key: "FundsDeposited"
  ): TypedContractEvent<
    FundsDepositedEvent.InputTuple,
    FundsDepositedEvent.OutputTuple,
    FundsDepositedEvent.OutputObject
  >;
  getEvent(
    key: "FundsWithdrawn"
  ): TypedContractEvent<
    FundsWithdrawnEvent.InputTuple,
    FundsWithdrawnEvent.OutputTuple,
    FundsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "PaymentBlocked"
  ): TypedContractEvent<
    PaymentBlockedEvent.InputTuple,
    PaymentBlockedEvent.OutputTuple,
    PaymentBlockedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentExecuted"
  ): TypedContractEvent<
    PaymentExecutedEvent.InputTuple,
    PaymentExecutedEvent.OutputTuple,
    PaymentExecutedEvent.OutputObject
  >;
  getEvent(
    key: "RemovedFromBlacklist"
  ): TypedContractEvent<
    RemovedFromBlacklistEvent.InputTuple,
    RemovedFromBlacklistEvent.OutputTuple,
    RemovedFromBlacklistEvent.OutputObject
  >;
  getEvent(
    key: "RemovedFromWhitelist"
  ): TypedContractEvent<
    RemovedFromWhitelistEvent.InputTuple,
    RemovedFromWhitelistEvent.OutputTuple,
    RemovedFromWhitelistEvent.OutputObject
  >;

  filters: {
    "AddedToBlacklist(address,address)": TypedContractEvent<
      AddedToBlacklistEvent.InputTuple,
      AddedToBlacklistEvent.OutputTuple,
      AddedToBlacklistEvent.OutputObject
    >;
    AddedToBlacklist: TypedContractEvent<
      AddedToBlacklistEvent.InputTuple,
      AddedToBlacklistEvent.OutputTuple,
      AddedToBlacklistEvent.OutputObject
    >;

    "AddedToWhitelist(address,address)": TypedContractEvent<
      AddedToWhitelistEvent.InputTuple,
      AddedToWhitelistEvent.OutputTuple,
      AddedToWhitelistEvent.OutputObject
    >;
    AddedToWhitelist: TypedContractEvent<
      AddedToWhitelistEvent.InputTuple,
      AddedToWhitelistEvent.OutputTuple,
      AddedToWhitelistEvent.OutputObject
    >;

    "AgentDeactivated(address)": TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;
    AgentDeactivated: TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;

    "AgentReactivated(address)": TypedContractEvent<
      AgentReactivatedEvent.InputTuple,
      AgentReactivatedEvent.OutputTuple,
      AgentReactivatedEvent.OutputObject
    >;
    AgentReactivated: TypedContractEvent<
      AgentReactivatedEvent.InputTuple,
      AgentReactivatedEvent.OutputTuple,
      AgentReactivatedEvent.OutputObject
    >;

    "AgentRegistered(address,address,uint256,uint256)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentUpdated(address,uint256,uint256)": TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;
    AgentUpdated: TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;

    "BudgetReset(address,uint256)": TypedContractEvent<
      BudgetResetEvent.InputTuple,
      BudgetResetEvent.OutputTuple,
      BudgetResetEvent.OutputObject
    >;
    BudgetReset: TypedContractEvent<
      BudgetResetEvent.InputTuple,
      BudgetResetEvent.OutputTuple,
      BudgetResetEvent.OutputObject
    >;

    "FundsDeposited(address,uint256)": TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;
    FundsDeposited: TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;

    "FundsWithdrawn(address,uint256)": TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;
    FundsWithdrawn: TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;

    "PaymentBlocked(address,address,uint256,string)": TypedContractEvent<
      PaymentBlockedEvent.InputTuple,
      PaymentBlockedEvent.OutputTuple,
      PaymentBlockedEvent.OutputObject
    >;
    PaymentBlocked: TypedContractEvent<
      PaymentBlockedEvent.InputTuple,
      PaymentBlockedEvent.OutputTuple,
      PaymentBlockedEvent.OutputObject
    >;

    "PaymentExecuted(address,address,uint256,string)": TypedContractEvent<
      PaymentExecutedEvent.InputTuple,
      PaymentExecutedEvent.OutputTuple,
      PaymentExecutedEvent.OutputObject
    >;
    PaymentExecuted: TypedContractEvent<
      PaymentExecutedEvent.InputTuple,
      PaymentExecutedEvent.OutputTuple,
      PaymentExecutedEvent.OutputObject
    >;

    "RemovedFromBlacklist(address,address)": TypedContractEvent<
      RemovedFromBlacklistEvent.InputTuple,
      RemovedFromBlacklistEvent.OutputTuple,
      RemovedFromBlacklistEvent.OutputObject
    >;
    RemovedFromBlacklist: TypedContractEvent<
      RemovedFromBlacklistEvent.InputTuple,
      RemovedFromBlacklistEvent.OutputTuple,
      RemovedFromBlacklistEvent.OutputObject
    >;

    "RemovedFromWhitelist(address,address)": TypedContractEvent<
      RemovedFromWhitelistEvent.InputTuple,
      RemovedFromWhitelistEvent.OutputTuple,
      RemovedFromWhitelistEvent.OutputObject
    >;
    RemovedFromWhitelist: TypedContractEvent<
      RemovedFromWhitelistEvent.InputTuple,
      RemovedFromWhitelistEvent.OutputTuple,
      RemovedFromWhitelistEvent.OutputObject
    >;
  };
}
