/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ArcPayPaymentChannel {
  export type ChannelStruct = {
    id: BytesLike;
    sender: AddressLike;
    recipient: AddressLike;
    deposit: BigNumberish;
    spent: BigNumberish;
    nonce: BigNumberish;
    state: BigNumberish;
    createdAt: BigNumberish;
    closingAt: BigNumberish;
    closedAt: BigNumberish;
  };

  export type ChannelStructOutput = [
    id: string,
    sender: string,
    recipient: string,
    deposit: bigint,
    spent: bigint,
    nonce: bigint,
    state: bigint,
    createdAt: bigint,
    closingAt: bigint,
    closedAt: bigint
  ] & {
    id: string;
    sender: string;
    recipient: string;
    deposit: bigint;
    spent: bigint;
    nonce: bigint;
    state: bigint;
    createdAt: bigint;
    closingAt: bigint;
    closedAt: bigint;
  };
}

export interface ArcPayPaymentChannelInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DISPUTE_PERIOD"
      | "MIN_DEPOSIT"
      | "channelCount"
      | "channels"
      | "closeChannel"
      | "cooperativeClose"
      | "disputeChannel"
      | "emergencyClose"
      | "finalizeClose"
      | "getChannel"
      | "getChannelBalance"
      | "getPaymentHash"
      | "getRecipientChannels"
      | "getSenderChannels"
      | "openChannel"
      | "recipientChannels"
      | "senderChannels"
      | "topUpChannel"
      | "verifyPayment"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ChannelClosed"
      | "ChannelClosing"
      | "ChannelDisputed"
      | "ChannelOpened"
      | "ChannelTopUp"
      | "PaymentSigned"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DISPUTE_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_DEPOSIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "channelCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "channels", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "closeChannel",
    values: [BytesLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cooperativeClose",
    values: [BytesLike, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeChannel",
    values: [BytesLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyClose",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeClose",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getChannel",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getChannelBalance",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPaymentHash",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecipientChannels",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSenderChannels",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "openChannel",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recipientChannels",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "senderChannels",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "topUpChannel",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyPayment",
    values: [BytesLike, BigNumberish, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DISPUTE_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_DEPOSIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "channelCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "channels", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "closeChannel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cooperativeClose",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeChannel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyClose",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeClose",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getChannel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getChannelBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPaymentHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecipientChannels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSenderChannels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openChannel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recipientChannels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "senderChannels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "topUpChannel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyPayment",
    data: BytesLike
  ): Result;
}

export namespace ChannelClosedEvent {
  export type InputTuple = [
    id: BytesLike,
    senderRefund: BigNumberish,
    recipientPayment: BigNumberish
  ];
  export type OutputTuple = [
    id: string,
    senderRefund: bigint,
    recipientPayment: bigint
  ];
  export interface OutputObject {
    id: string;
    senderRefund: bigint;
    recipientPayment: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChannelClosingEvent {
  export type InputTuple = [
    id: BytesLike,
    spent: BigNumberish,
    closingAt: BigNumberish
  ];
  export type OutputTuple = [id: string, spent: bigint, closingAt: bigint];
  export interface OutputObject {
    id: string;
    spent: bigint;
    closingAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChannelDisputedEvent {
  export type InputTuple = [
    id: BytesLike,
    newSpent: BigNumberish,
    newNonce: BigNumberish
  ];
  export type OutputTuple = [id: string, newSpent: bigint, newNonce: bigint];
  export interface OutputObject {
    id: string;
    newSpent: bigint;
    newNonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChannelOpenedEvent {
  export type InputTuple = [
    id: BytesLike,
    sender: AddressLike,
    recipient: AddressLike,
    deposit: BigNumberish
  ];
  export type OutputTuple = [
    id: string,
    sender: string,
    recipient: string,
    deposit: bigint
  ];
  export interface OutputObject {
    id: string;
    sender: string;
    recipient: string;
    deposit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChannelTopUpEvent {
  export type InputTuple = [
    id: BytesLike,
    additionalDeposit: BigNumberish,
    newTotal: BigNumberish
  ];
  export type OutputTuple = [
    id: string,
    additionalDeposit: bigint,
    newTotal: bigint
  ];
  export interface OutputObject {
    id: string;
    additionalDeposit: bigint;
    newTotal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentSignedEvent {
  export type InputTuple = [
    channelId: BytesLike,
    amount: BigNumberish,
    totalSpent: BigNumberish,
    nonce: BigNumberish
  ];
  export type OutputTuple = [
    channelId: string,
    amount: bigint,
    totalSpent: bigint,
    nonce: bigint
  ];
  export interface OutputObject {
    channelId: string;
    amount: bigint;
    totalSpent: bigint;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArcPayPaymentChannel extends BaseContract {
  connect(runner?: ContractRunner | null): ArcPayPaymentChannel;
  waitForDeployment(): Promise<this>;

  interface: ArcPayPaymentChannelInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DISPUTE_PERIOD: TypedContractMethod<[], [bigint], "view">;

  MIN_DEPOSIT: TypedContractMethod<[], [bigint], "view">;

  channelCount: TypedContractMethod<[], [bigint], "view">;

  channels: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: string;
        sender: string;
        recipient: string;
        deposit: bigint;
        spent: bigint;
        nonce: bigint;
        state: bigint;
        createdAt: bigint;
        closingAt: bigint;
        closedAt: bigint;
      }
    ],
    "view"
  >;

  closeChannel: TypedContractMethod<
    [
      channelId: BytesLike,
      spent: BigNumberish,
      nonce: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  cooperativeClose: TypedContractMethod<
    [
      channelId: BytesLike,
      spent: BigNumberish,
      senderSignature: BytesLike,
      recipientSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  disputeChannel: TypedContractMethod<
    [
      channelId: BytesLike,
      spent: BigNumberish,
      nonce: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  emergencyClose: TypedContractMethod<
    [channelId: BytesLike],
    [void],
    "nonpayable"
  >;

  finalizeClose: TypedContractMethod<
    [channelId: BytesLike],
    [void],
    "nonpayable"
  >;

  getChannel: TypedContractMethod<
    [channelId: BytesLike],
    [ArcPayPaymentChannel.ChannelStructOutput],
    "view"
  >;

  getChannelBalance: TypedContractMethod<
    [channelId: BytesLike],
    [[bigint, bigint] & { available: bigint; spent: bigint }],
    "view"
  >;

  getPaymentHash: TypedContractMethod<
    [channelId: BytesLike, spent: BigNumberish, nonce: BigNumberish],
    [string],
    "view"
  >;

  getRecipientChannels: TypedContractMethod<
    [recipient: AddressLike],
    [string[]],
    "view"
  >;

  getSenderChannels: TypedContractMethod<
    [sender: AddressLike],
    [string[]],
    "view"
  >;

  openChannel: TypedContractMethod<
    [recipient: AddressLike, deposit: BigNumberish],
    [string],
    "payable"
  >;

  recipientChannels: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  senderChannels: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  topUpChannel: TypedContractMethod<[channelId: BytesLike], [void], "payable">;

  verifyPayment: TypedContractMethod<
    [
      channelId: BytesLike,
      spent: BigNumberish,
      nonce: BigNumberish,
      signature: BytesLike
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DISPUTE_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_DEPOSIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "channelCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "channels"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: string;
        sender: string;
        recipient: string;
        deposit: bigint;
        spent: bigint;
        nonce: bigint;
        state: bigint;
        createdAt: bigint;
        closingAt: bigint;
        closedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "closeChannel"
  ): TypedContractMethod<
    [
      channelId: BytesLike,
      spent: BigNumberish,
      nonce: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cooperativeClose"
  ): TypedContractMethod<
    [
      channelId: BytesLike,
      spent: BigNumberish,
      senderSignature: BytesLike,
      recipientSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disputeChannel"
  ): TypedContractMethod<
    [
      channelId: BytesLike,
      spent: BigNumberish,
      nonce: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyClose"
  ): TypedContractMethod<[channelId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizeClose"
  ): TypedContractMethod<[channelId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getChannel"
  ): TypedContractMethod<
    [channelId: BytesLike],
    [ArcPayPaymentChannel.ChannelStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getChannelBalance"
  ): TypedContractMethod<
    [channelId: BytesLike],
    [[bigint, bigint] & { available: bigint; spent: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPaymentHash"
  ): TypedContractMethod<
    [channelId: BytesLike, spent: BigNumberish, nonce: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecipientChannels"
  ): TypedContractMethod<[recipient: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getSenderChannels"
  ): TypedContractMethod<[sender: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "openChannel"
  ): TypedContractMethod<
    [recipient: AddressLike, deposit: BigNumberish],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "recipientChannels"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "senderChannels"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "topUpChannel"
  ): TypedContractMethod<[channelId: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "verifyPayment"
  ): TypedContractMethod<
    [
      channelId: BytesLike,
      spent: BigNumberish,
      nonce: BigNumberish,
      signature: BytesLike
    ],
    [boolean],
    "view"
  >;

  getEvent(
    key: "ChannelClosed"
  ): TypedContractEvent<
    ChannelClosedEvent.InputTuple,
    ChannelClosedEvent.OutputTuple,
    ChannelClosedEvent.OutputObject
  >;
  getEvent(
    key: "ChannelClosing"
  ): TypedContractEvent<
    ChannelClosingEvent.InputTuple,
    ChannelClosingEvent.OutputTuple,
    ChannelClosingEvent.OutputObject
  >;
  getEvent(
    key: "ChannelDisputed"
  ): TypedContractEvent<
    ChannelDisputedEvent.InputTuple,
    ChannelDisputedEvent.OutputTuple,
    ChannelDisputedEvent.OutputObject
  >;
  getEvent(
    key: "ChannelOpened"
  ): TypedContractEvent<
    ChannelOpenedEvent.InputTuple,
    ChannelOpenedEvent.OutputTuple,
    ChannelOpenedEvent.OutputObject
  >;
  getEvent(
    key: "ChannelTopUp"
  ): TypedContractEvent<
    ChannelTopUpEvent.InputTuple,
    ChannelTopUpEvent.OutputTuple,
    ChannelTopUpEvent.OutputObject
  >;
  getEvent(
    key: "PaymentSigned"
  ): TypedContractEvent<
    PaymentSignedEvent.InputTuple,
    PaymentSignedEvent.OutputTuple,
    PaymentSignedEvent.OutputObject
  >;

  filters: {
    "ChannelClosed(bytes32,uint256,uint256)": TypedContractEvent<
      ChannelClosedEvent.InputTuple,
      ChannelClosedEvent.OutputTuple,
      ChannelClosedEvent.OutputObject
    >;
    ChannelClosed: TypedContractEvent<
      ChannelClosedEvent.InputTuple,
      ChannelClosedEvent.OutputTuple,
      ChannelClosedEvent.OutputObject
    >;

    "ChannelClosing(bytes32,uint256,uint256)": TypedContractEvent<
      ChannelClosingEvent.InputTuple,
      ChannelClosingEvent.OutputTuple,
      ChannelClosingEvent.OutputObject
    >;
    ChannelClosing: TypedContractEvent<
      ChannelClosingEvent.InputTuple,
      ChannelClosingEvent.OutputTuple,
      ChannelClosingEvent.OutputObject
    >;

    "ChannelDisputed(bytes32,uint256,uint256)": TypedContractEvent<
      ChannelDisputedEvent.InputTuple,
      ChannelDisputedEvent.OutputTuple,
      ChannelDisputedEvent.OutputObject
    >;
    ChannelDisputed: TypedContractEvent<
      ChannelDisputedEvent.InputTuple,
      ChannelDisputedEvent.OutputTuple,
      ChannelDisputedEvent.OutputObject
    >;

    "ChannelOpened(bytes32,address,address,uint256)": TypedContractEvent<
      ChannelOpenedEvent.InputTuple,
      ChannelOpenedEvent.OutputTuple,
      ChannelOpenedEvent.OutputObject
    >;
    ChannelOpened: TypedContractEvent<
      ChannelOpenedEvent.InputTuple,
      ChannelOpenedEvent.OutputTuple,
      ChannelOpenedEvent.OutputObject
    >;

    "ChannelTopUp(bytes32,uint256,uint256)": TypedContractEvent<
      ChannelTopUpEvent.InputTuple,
      ChannelTopUpEvent.OutputTuple,
      ChannelTopUpEvent.OutputObject
    >;
    ChannelTopUp: TypedContractEvent<
      ChannelTopUpEvent.InputTuple,
      ChannelTopUpEvent.OutputTuple,
      ChannelTopUpEvent.OutputObject
    >;

    "PaymentSigned(bytes32,uint256,uint256,uint256)": TypedContractEvent<
      PaymentSignedEvent.InputTuple,
      PaymentSignedEvent.OutputTuple,
      PaymentSignedEvent.OutputObject
    >;
    PaymentSigned: TypedContractEvent<
      PaymentSignedEvent.InputTuple,
      PaymentSignedEvent.OutputTuple,
      PaymentSignedEvent.OutputObject
    >;
  };
}
