/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ArcPayStealthRegistry {
  export type AnnouncementStruct = {
    id: BytesLike;
    stealthAddress: AddressLike;
    amount: BigNumberish;
    ephemeralPubKey: BytesLike;
    encryptedMemo: BytesLike;
    timestamp: BigNumberish;
    claimed: boolean;
  };

  export type AnnouncementStructOutput = [
    id: string,
    stealthAddress: string,
    amount: bigint,
    ephemeralPubKey: string,
    encryptedMemo: string,
    timestamp: bigint,
    claimed: boolean
  ] & {
    id: string;
    stealthAddress: string;
    amount: bigint;
    ephemeralPubKey: string;
    encryptedMemo: string;
    timestamp: bigint;
    claimed: boolean;
  };

  export type StealthMetaAddressStruct = {
    spendingPubKey: BytesLike;
    viewingPubKey: BytesLike;
    registeredAt: BigNumberish;
    active: boolean;
  };

  export type StealthMetaAddressStructOutput = [
    spendingPubKey: string,
    viewingPubKey: string,
    registeredAt: bigint,
    active: boolean
  ] & {
    spendingPubKey: string;
    viewingPubKey: string;
    registeredAt: bigint;
    active: boolean;
  };
}

export interface ArcPayStealthRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allAnnouncements"
      | "announcementCount"
      | "announcements"
      | "deactivateMetaAddress"
      | "getAnnouncement"
      | "getAnnouncements"
      | "getMetaAddress"
      | "getNewAnnouncements"
      | "getTotalAnnouncements"
      | "isRegistered"
      | "lastScannedIndex"
      | "markClaimed"
      | "metaAddresses"
      | "reactivateMetaAddress"
      | "registerMetaAddress"
      | "sendStealthPayment"
      | "updateLastScanned"
      | "updateMetaAddress"
      | "userAnnouncements"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MetaAddressDeactivated"
      | "MetaAddressRegistered"
      | "MetaAddressUpdated"
      | "PaymentClaimed"
      | "StealthPayment"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allAnnouncements",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "announcementCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "announcements",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateMetaAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAnnouncement",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAnnouncements",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMetaAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNewAnnouncements",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalAnnouncements",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastScannedIndex",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markClaimed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "metaAddresses",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reactivateMetaAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerMetaAddress",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sendStealthPayment",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLastScanned",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMetaAddress",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userAnnouncements",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "allAnnouncements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "announcementCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "announcements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateMetaAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAnnouncement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAnnouncements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMetaAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNewAnnouncements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalAnnouncements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastScannedIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metaAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reactivateMetaAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerMetaAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendStealthPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLastScanned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMetaAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userAnnouncements",
    data: BytesLike
  ): Result;
}

export namespace MetaAddressDeactivatedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MetaAddressRegisteredEvent {
  export type InputTuple = [
    user: AddressLike,
    spendingPubKey: BytesLike,
    viewingPubKey: BytesLike
  ];
  export type OutputTuple = [
    user: string,
    spendingPubKey: string,
    viewingPubKey: string
  ];
  export interface OutputObject {
    user: string;
    spendingPubKey: string;
    viewingPubKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MetaAddressUpdatedEvent {
  export type InputTuple = [
    user: AddressLike,
    spendingPubKey: BytesLike,
    viewingPubKey: BytesLike
  ];
  export type OutputTuple = [
    user: string,
    spendingPubKey: string,
    viewingPubKey: string
  ];
  export interface OutputObject {
    user: string;
    spendingPubKey: string;
    viewingPubKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentClaimedEvent {
  export type InputTuple = [
    id: BytesLike,
    stealthAddress: AddressLike,
    claimer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    id: string,
    stealthAddress: string,
    claimer: string,
    amount: bigint
  ];
  export interface OutputObject {
    id: string;
    stealthAddress: string;
    claimer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StealthPaymentEvent {
  export type InputTuple = [
    id: BytesLike,
    stealthAddress: AddressLike,
    amount: BigNumberish,
    ephemeralPubKey: BytesLike,
    encryptedMemo: BytesLike
  ];
  export type OutputTuple = [
    id: string,
    stealthAddress: string,
    amount: bigint,
    ephemeralPubKey: string,
    encryptedMemo: string
  ];
  export interface OutputObject {
    id: string;
    stealthAddress: string;
    amount: bigint;
    ephemeralPubKey: string;
    encryptedMemo: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArcPayStealthRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ArcPayStealthRegistry;
  waitForDeployment(): Promise<this>;

  interface: ArcPayStealthRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allAnnouncements: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  announcementCount: TypedContractMethod<[], [bigint], "view">;

  announcements: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, string, string, bigint, boolean] & {
        id: string;
        stealthAddress: string;
        amount: bigint;
        ephemeralPubKey: string;
        encryptedMemo: string;
        timestamp: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;

  deactivateMetaAddress: TypedContractMethod<[], [void], "nonpayable">;

  getAnnouncement: TypedContractMethod<
    [id: BytesLike],
    [ArcPayStealthRegistry.AnnouncementStructOutput],
    "view"
  >;

  getAnnouncements: TypedContractMethod<
    [fromIndex: BigNumberish, count: BigNumberish],
    [ArcPayStealthRegistry.AnnouncementStructOutput[]],
    "view"
  >;

  getMetaAddress: TypedContractMethod<
    [user: AddressLike],
    [ArcPayStealthRegistry.StealthMetaAddressStructOutput],
    "view"
  >;

  getNewAnnouncements: TypedContractMethod<
    [count: BigNumberish],
    [
      [ArcPayStealthRegistry.AnnouncementStructOutput[], bigint] & {
        newLastIndex: bigint;
      }
    ],
    "view"
  >;

  getTotalAnnouncements: TypedContractMethod<[], [bigint], "view">;

  isRegistered: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  lastScannedIndex: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  markClaimed: TypedContractMethod<
    [announcementId: BytesLike],
    [void],
    "nonpayable"
  >;

  metaAddresses: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, boolean] & {
        spendingPubKey: string;
        viewingPubKey: string;
        registeredAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  reactivateMetaAddress: TypedContractMethod<[], [void], "nonpayable">;

  registerMetaAddress: TypedContractMethod<
    [spendingPubKey: BytesLike, viewingPubKey: BytesLike],
    [void],
    "nonpayable"
  >;

  sendStealthPayment: TypedContractMethod<
    [
      stealthAddress: AddressLike,
      ephemeralPubKey: BytesLike,
      encryptedMemo: BytesLike
    ],
    [string],
    "payable"
  >;

  updateLastScanned: TypedContractMethod<
    [index: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateMetaAddress: TypedContractMethod<
    [spendingPubKey: BytesLike, viewingPubKey: BytesLike],
    [void],
    "nonpayable"
  >;

  userAnnouncements: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allAnnouncements"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "announcementCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "announcements"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, string, string, bigint, boolean] & {
        id: string;
        stealthAddress: string;
        amount: bigint;
        ephemeralPubKey: string;
        encryptedMemo: string;
        timestamp: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "deactivateMetaAddress"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAnnouncement"
  ): TypedContractMethod<
    [id: BytesLike],
    [ArcPayStealthRegistry.AnnouncementStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAnnouncements"
  ): TypedContractMethod<
    [fromIndex: BigNumberish, count: BigNumberish],
    [ArcPayStealthRegistry.AnnouncementStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMetaAddress"
  ): TypedContractMethod<
    [user: AddressLike],
    [ArcPayStealthRegistry.StealthMetaAddressStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNewAnnouncements"
  ): TypedContractMethod<
    [count: BigNumberish],
    [
      [ArcPayStealthRegistry.AnnouncementStructOutput[], bigint] & {
        newLastIndex: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalAnnouncements"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastScannedIndex"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "markClaimed"
  ): TypedContractMethod<[announcementId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "metaAddresses"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, boolean] & {
        spendingPubKey: string;
        viewingPubKey: string;
        registeredAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "reactivateMetaAddress"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerMetaAddress"
  ): TypedContractMethod<
    [spendingPubKey: BytesLike, viewingPubKey: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sendStealthPayment"
  ): TypedContractMethod<
    [
      stealthAddress: AddressLike,
      ephemeralPubKey: BytesLike,
      encryptedMemo: BytesLike
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "updateLastScanned"
  ): TypedContractMethod<[index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateMetaAddress"
  ): TypedContractMethod<
    [spendingPubKey: BytesLike, viewingPubKey: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userAnnouncements"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getEvent(
    key: "MetaAddressDeactivated"
  ): TypedContractEvent<
    MetaAddressDeactivatedEvent.InputTuple,
    MetaAddressDeactivatedEvent.OutputTuple,
    MetaAddressDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "MetaAddressRegistered"
  ): TypedContractEvent<
    MetaAddressRegisteredEvent.InputTuple,
    MetaAddressRegisteredEvent.OutputTuple,
    MetaAddressRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "MetaAddressUpdated"
  ): TypedContractEvent<
    MetaAddressUpdatedEvent.InputTuple,
    MetaAddressUpdatedEvent.OutputTuple,
    MetaAddressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentClaimed"
  ): TypedContractEvent<
    PaymentClaimedEvent.InputTuple,
    PaymentClaimedEvent.OutputTuple,
    PaymentClaimedEvent.OutputObject
  >;
  getEvent(
    key: "StealthPayment"
  ): TypedContractEvent<
    StealthPaymentEvent.InputTuple,
    StealthPaymentEvent.OutputTuple,
    StealthPaymentEvent.OutputObject
  >;

  filters: {
    "MetaAddressDeactivated(address)": TypedContractEvent<
      MetaAddressDeactivatedEvent.InputTuple,
      MetaAddressDeactivatedEvent.OutputTuple,
      MetaAddressDeactivatedEvent.OutputObject
    >;
    MetaAddressDeactivated: TypedContractEvent<
      MetaAddressDeactivatedEvent.InputTuple,
      MetaAddressDeactivatedEvent.OutputTuple,
      MetaAddressDeactivatedEvent.OutputObject
    >;

    "MetaAddressRegistered(address,bytes,bytes)": TypedContractEvent<
      MetaAddressRegisteredEvent.InputTuple,
      MetaAddressRegisteredEvent.OutputTuple,
      MetaAddressRegisteredEvent.OutputObject
    >;
    MetaAddressRegistered: TypedContractEvent<
      MetaAddressRegisteredEvent.InputTuple,
      MetaAddressRegisteredEvent.OutputTuple,
      MetaAddressRegisteredEvent.OutputObject
    >;

    "MetaAddressUpdated(address,bytes,bytes)": TypedContractEvent<
      MetaAddressUpdatedEvent.InputTuple,
      MetaAddressUpdatedEvent.OutputTuple,
      MetaAddressUpdatedEvent.OutputObject
    >;
    MetaAddressUpdated: TypedContractEvent<
      MetaAddressUpdatedEvent.InputTuple,
      MetaAddressUpdatedEvent.OutputTuple,
      MetaAddressUpdatedEvent.OutputObject
    >;

    "PaymentClaimed(bytes32,address,address,uint256)": TypedContractEvent<
      PaymentClaimedEvent.InputTuple,
      PaymentClaimedEvent.OutputTuple,
      PaymentClaimedEvent.OutputObject
    >;
    PaymentClaimed: TypedContractEvent<
      PaymentClaimedEvent.InputTuple,
      PaymentClaimedEvent.OutputTuple,
      PaymentClaimedEvent.OutputObject
    >;

    "StealthPayment(bytes32,address,uint256,bytes,bytes)": TypedContractEvent<
      StealthPaymentEvent.InputTuple,
      StealthPaymentEvent.OutputTuple,
      StealthPaymentEvent.OutputObject
    >;
    StealthPayment: TypedContractEvent<
      StealthPaymentEvent.InputTuple,
      StealthPaymentEvent.OutputTuple,
      StealthPaymentEvent.OutputObject
    >;
  };
}
