/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ArcPayEscrow {
  export type DisputeStruct = {
    escrowId: BytesLike;
    initiator: AddressLike;
    reason: string;
    createdAt: BigNumberish;
    resolved: boolean;
    winner: AddressLike;
    depositorShare: BigNumberish;
    beneficiaryShare: BigNumberish;
  };

  export type DisputeStructOutput = [
    escrowId: string,
    initiator: string,
    reason: string,
    createdAt: bigint,
    resolved: boolean,
    winner: string,
    depositorShare: bigint,
    beneficiaryShare: bigint
  ] & {
    escrowId: string;
    initiator: string;
    reason: string;
    createdAt: bigint;
    resolved: boolean;
    winner: string;
    depositorShare: bigint;
    beneficiaryShare: bigint;
  };

  export type EscrowStruct = {
    id: BytesLike;
    depositor: AddressLike;
    beneficiary: AddressLike;
    arbiter: AddressLike;
    amount: BigNumberish;
    fundedAt: BigNumberish;
    expiresAt: BigNumberish;
    state: BigNumberish;
    conditionHash: string;
    releasedAmount: BigNumberish;
    refundedAmount: BigNumberish;
  };

  export type EscrowStructOutput = [
    id: string,
    depositor: string,
    beneficiary: string,
    arbiter: string,
    amount: bigint,
    fundedAt: bigint,
    expiresAt: bigint,
    state: bigint,
    conditionHash: string,
    releasedAmount: bigint,
    refundedAmount: bigint
  ] & {
    id: string;
    depositor: string;
    beneficiary: string;
    arbiter: string;
    amount: bigint;
    fundedAt: bigint;
    expiresAt: bigint;
    state: bigint;
    conditionHash: string;
    releasedAmount: bigint;
    refundedAmount: bigint;
  };

  export type MilestoneStruct = {
    amount: BigNumberish;
    description: string;
    completed: boolean;
    completedAt: BigNumberish;
  };

  export type MilestoneStructOutput = [
    amount: bigint,
    description: string,
    completed: boolean,
    completedAt: bigint
  ] & {
    amount: bigint;
    description: string;
    completed: boolean;
    completedAt: bigint;
  };
}

export interface ArcPayEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addMilestones"
      | "completeMilestone"
      | "createAndFundEscrow"
      | "createDispute"
      | "createEscrow"
      | "disputeFee"
      | "disputes"
      | "escrowCount"
      | "escrows"
      | "feeCollector"
      | "fundEscrow"
      | "getDispute"
      | "getEscrow"
      | "getMilestones"
      | "getUserEscrows"
      | "milestones"
      | "owner"
      | "refundEscrow"
      | "releaseEscrow"
      | "renounceOwnership"
      | "resolveDispute"
      | "setDisputeFee"
      | "setFeeCollector"
      | "transferOwnership"
      | "userEscrows"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DisputeCreated"
      | "DisputeResolved"
      | "EscrowCreated"
      | "EscrowFunded"
      | "EscrowRefunded"
      | "EscrowReleased"
      | "MilestoneAdded"
      | "MilestoneCompleted"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addMilestones",
    values: [BytesLike, BigNumberish[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "completeMilestone",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createAndFundEscrow",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createDispute",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createEscrow",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeFee",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "disputes", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "escrowCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "escrows", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "feeCollector",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fundEscrow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDispute",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMilestones",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserEscrows",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "milestones",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "refundEscrow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseEscrow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDisputeFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeCollector",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userEscrows",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addMilestones",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAndFundEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "disputeFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "disputes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "escrowCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundEscrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getDispute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getEscrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMilestones",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserEscrows",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "milestones", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refundEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDisputeFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userEscrows",
    data: BytesLike
  ): Result;
}

export namespace DisputeCreatedEvent {
  export type InputTuple = [
    escrowId: BytesLike,
    initiator: AddressLike,
    reason: string
  ];
  export type OutputTuple = [
    escrowId: string,
    initiator: string,
    reason: string
  ];
  export interface OutputObject {
    escrowId: string;
    initiator: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    escrowId: BytesLike,
    winner: AddressLike,
    depositorShare: BigNumberish,
    beneficiaryShare: BigNumberish
  ];
  export type OutputTuple = [
    escrowId: string,
    winner: string,
    depositorShare: bigint,
    beneficiaryShare: bigint
  ];
  export interface OutputObject {
    escrowId: string;
    winner: string;
    depositorShare: bigint;
    beneficiaryShare: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowCreatedEvent {
  export type InputTuple = [
    id: BytesLike,
    depositor: AddressLike,
    beneficiary: AddressLike,
    arbiter: AddressLike,
    amount: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    id: string,
    depositor: string,
    beneficiary: string,
    arbiter: string,
    amount: bigint,
    expiresAt: bigint
  ];
  export interface OutputObject {
    id: string;
    depositor: string;
    beneficiary: string;
    arbiter: string;
    amount: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowFundedEvent {
  export type InputTuple = [
    id: BytesLike,
    amount: BigNumberish,
    fundedAt: BigNumberish
  ];
  export type OutputTuple = [id: string, amount: bigint, fundedAt: bigint];
  export interface OutputObject {
    id: string;
    amount: bigint;
    fundedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowRefundedEvent {
  export type InputTuple = [
    id: BytesLike,
    depositor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [id: string, depositor: string, amount: bigint];
  export interface OutputObject {
    id: string;
    depositor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowReleasedEvent {
  export type InputTuple = [
    id: BytesLike,
    beneficiary: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [id: string, beneficiary: string, amount: bigint];
  export interface OutputObject {
    id: string;
    beneficiary: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneAddedEvent {
  export type InputTuple = [
    escrowId: BytesLike,
    index: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [escrowId: string, index: bigint, amount: bigint];
  export interface OutputObject {
    escrowId: string;
    index: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneCompletedEvent {
  export type InputTuple = [
    escrowId: BytesLike,
    index: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [escrowId: string, index: bigint, amount: bigint];
  export interface OutputObject {
    escrowId: string;
    index: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArcPayEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): ArcPayEscrow;
  waitForDeployment(): Promise<this>;

  interface: ArcPayEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addMilestones: TypedContractMethod<
    [escrowId: BytesLike, amounts: BigNumberish[], descriptions: string[]],
    [void],
    "nonpayable"
  >;

  completeMilestone: TypedContractMethod<
    [escrowId: BytesLike, milestoneIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  createAndFundEscrow: TypedContractMethod<
    [
      beneficiary: AddressLike,
      arbiter: AddressLike,
      amount: BigNumberish,
      expiresAt: BigNumberish,
      conditionHash: string
    ],
    [string],
    "payable"
  >;

  createDispute: TypedContractMethod<
    [escrowId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  createEscrow: TypedContractMethod<
    [
      beneficiary: AddressLike,
      arbiter: AddressLike,
      amount: BigNumberish,
      expiresAt: BigNumberish,
      conditionHash: string
    ],
    [string],
    "nonpayable"
  >;

  disputeFee: TypedContractMethod<[], [bigint], "view">;

  disputes: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, boolean, string, bigint, bigint] & {
        escrowId: string;
        initiator: string;
        reason: string;
        createdAt: bigint;
        resolved: boolean;
        winner: string;
        depositorShare: bigint;
        beneficiaryShare: bigint;
      }
    ],
    "view"
  >;

  escrowCount: TypedContractMethod<[], [bigint], "view">;

  escrows: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        id: string;
        depositor: string;
        beneficiary: string;
        arbiter: string;
        amount: bigint;
        fundedAt: bigint;
        expiresAt: bigint;
        state: bigint;
        conditionHash: string;
        releasedAmount: bigint;
        refundedAmount: bigint;
      }
    ],
    "view"
  >;

  feeCollector: TypedContractMethod<[], [string], "view">;

  fundEscrow: TypedContractMethod<[escrowId: BytesLike], [void], "payable">;

  getDispute: TypedContractMethod<
    [escrowId: BytesLike],
    [ArcPayEscrow.DisputeStructOutput],
    "view"
  >;

  getEscrow: TypedContractMethod<
    [escrowId: BytesLike],
    [ArcPayEscrow.EscrowStructOutput],
    "view"
  >;

  getMilestones: TypedContractMethod<
    [escrowId: BytesLike],
    [ArcPayEscrow.MilestoneStructOutput[]],
    "view"
  >;

  getUserEscrows: TypedContractMethod<[user: AddressLike], [string[]], "view">;

  milestones: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [bigint, string, boolean, bigint] & {
        amount: bigint;
        description: string;
        completed: boolean;
        completedAt: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  refundEscrow: TypedContractMethod<
    [escrowId: BytesLike],
    [void],
    "nonpayable"
  >;

  releaseEscrow: TypedContractMethod<
    [escrowId: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveDispute: TypedContractMethod<
    [
      escrowId: BytesLike,
      depositorShare: BigNumberish,
      beneficiaryShare: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setDisputeFee: TypedContractMethod<
    [_disputeFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFeeCollector: TypedContractMethod<
    [_feeCollector: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userEscrows: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addMilestones"
  ): TypedContractMethod<
    [escrowId: BytesLike, amounts: BigNumberish[], descriptions: string[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "completeMilestone"
  ): TypedContractMethod<
    [escrowId: BytesLike, milestoneIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createAndFundEscrow"
  ): TypedContractMethod<
    [
      beneficiary: AddressLike,
      arbiter: AddressLike,
      amount: BigNumberish,
      expiresAt: BigNumberish,
      conditionHash: string
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createDispute"
  ): TypedContractMethod<
    [escrowId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createEscrow"
  ): TypedContractMethod<
    [
      beneficiary: AddressLike,
      arbiter: AddressLike,
      amount: BigNumberish,
      expiresAt: BigNumberish,
      conditionHash: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disputeFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "disputes"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, boolean, string, bigint, bigint] & {
        escrowId: string;
        initiator: string;
        reason: string;
        createdAt: bigint;
        resolved: boolean;
        winner: string;
        depositorShare: bigint;
        beneficiaryShare: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "escrowCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        id: string;
        depositor: string;
        beneficiary: string;
        arbiter: string;
        amount: bigint;
        fundedAt: bigint;
        expiresAt: bigint;
        state: bigint;
        conditionHash: string;
        releasedAmount: bigint;
        refundedAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "feeCollector"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fundEscrow"
  ): TypedContractMethod<[escrowId: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "getDispute"
  ): TypedContractMethod<
    [escrowId: BytesLike],
    [ArcPayEscrow.DisputeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEscrow"
  ): TypedContractMethod<
    [escrowId: BytesLike],
    [ArcPayEscrow.EscrowStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMilestones"
  ): TypedContractMethod<
    [escrowId: BytesLike],
    [ArcPayEscrow.MilestoneStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserEscrows"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "milestones"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [bigint, string, boolean, bigint] & {
        amount: bigint;
        description: string;
        completed: boolean;
        completedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refundEscrow"
  ): TypedContractMethod<[escrowId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releaseEscrow"
  ): TypedContractMethod<[escrowId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [
      escrowId: BytesLike,
      depositorShare: BigNumberish,
      beneficiaryShare: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDisputeFee"
  ): TypedContractMethod<[_disputeFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeCollector"
  ): TypedContractMethod<[_feeCollector: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userEscrows"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getEvent(
    key: "DisputeCreated"
  ): TypedContractEvent<
    DisputeCreatedEvent.InputTuple,
    DisputeCreatedEvent.OutputTuple,
    DisputeCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowCreated"
  ): TypedContractEvent<
    EscrowCreatedEvent.InputTuple,
    EscrowCreatedEvent.OutputTuple,
    EscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowFunded"
  ): TypedContractEvent<
    EscrowFundedEvent.InputTuple,
    EscrowFundedEvent.OutputTuple,
    EscrowFundedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowRefunded"
  ): TypedContractEvent<
    EscrowRefundedEvent.InputTuple,
    EscrowRefundedEvent.OutputTuple,
    EscrowRefundedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowReleased"
  ): TypedContractEvent<
    EscrowReleasedEvent.InputTuple,
    EscrowReleasedEvent.OutputTuple,
    EscrowReleasedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneAdded"
  ): TypedContractEvent<
    MilestoneAddedEvent.InputTuple,
    MilestoneAddedEvent.OutputTuple,
    MilestoneAddedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneCompleted"
  ): TypedContractEvent<
    MilestoneCompletedEvent.InputTuple,
    MilestoneCompletedEvent.OutputTuple,
    MilestoneCompletedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "DisputeCreated(bytes32,address,string)": TypedContractEvent<
      DisputeCreatedEvent.InputTuple,
      DisputeCreatedEvent.OutputTuple,
      DisputeCreatedEvent.OutputObject
    >;
    DisputeCreated: TypedContractEvent<
      DisputeCreatedEvent.InputTuple,
      DisputeCreatedEvent.OutputTuple,
      DisputeCreatedEvent.OutputObject
    >;

    "DisputeResolved(bytes32,address,uint256,uint256)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "EscrowCreated(bytes32,address,address,address,uint256,uint256)": TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;
    EscrowCreated: TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;

    "EscrowFunded(bytes32,uint256,uint256)": TypedContractEvent<
      EscrowFundedEvent.InputTuple,
      EscrowFundedEvent.OutputTuple,
      EscrowFundedEvent.OutputObject
    >;
    EscrowFunded: TypedContractEvent<
      EscrowFundedEvent.InputTuple,
      EscrowFundedEvent.OutputTuple,
      EscrowFundedEvent.OutputObject
    >;

    "EscrowRefunded(bytes32,address,uint256)": TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;
    EscrowRefunded: TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;

    "EscrowReleased(bytes32,address,uint256)": TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;
    EscrowReleased: TypedContractEvent<
      EscrowReleasedEvent.InputTuple,
      EscrowReleasedEvent.OutputTuple,
      EscrowReleasedEvent.OutputObject
    >;

    "MilestoneAdded(bytes32,uint256,uint256)": TypedContractEvent<
      MilestoneAddedEvent.InputTuple,
      MilestoneAddedEvent.OutputTuple,
      MilestoneAddedEvent.OutputObject
    >;
    MilestoneAdded: TypedContractEvent<
      MilestoneAddedEvent.InputTuple,
      MilestoneAddedEvent.OutputTuple,
      MilestoneAddedEvent.OutputObject
    >;

    "MilestoneCompleted(bytes32,uint256,uint256)": TypedContractEvent<
      MilestoneCompletedEvent.InputTuple,
      MilestoneCompletedEvent.OutputTuple,
      MilestoneCompletedEvent.OutputObject
    >;
    MilestoneCompleted: TypedContractEvent<
      MilestoneCompletedEvent.InputTuple,
      MilestoneCompletedEvent.OutputTuple,
      MilestoneCompletedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
