/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ArcPayStreamPayment {
  export type StreamStruct = {
    id: BytesLike;
    sender: AddressLike;
    recipient: AddressLike;
    totalAmount: BigNumberish;
    claimedAmount: BigNumberish;
    ratePerSecond: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    pausedAt: BigNumberish;
    pausedDuration: BigNumberish;
    state: BigNumberish;
  };

  export type StreamStructOutput = [
    id: string,
    sender: string,
    recipient: string,
    totalAmount: bigint,
    claimedAmount: bigint,
    ratePerSecond: bigint,
    startTime: bigint,
    endTime: bigint,
    pausedAt: bigint,
    pausedDuration: bigint,
    state: bigint
  ] & {
    id: string;
    sender: string;
    recipient: string;
    totalAmount: bigint;
    claimedAmount: bigint;
    ratePerSecond: bigint;
    startTime: bigint;
    endTime: bigint;
    pausedAt: bigint;
    pausedDuration: bigint;
    state: bigint;
  };
}

export interface ArcPayStreamPaymentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelStream"
      | "claim"
      | "createScheduledStream"
      | "createStream"
      | "feeCollector"
      | "getClaimableAmount"
      | "getRecipientStreams"
      | "getSenderStreams"
      | "getStream"
      | "getStreamProgress"
      | "pauseStream"
      | "protocolFee"
      | "recipientStreams"
      | "resumeStream"
      | "senderStreams"
      | "setFeeCollector"
      | "setProtocolFee"
      | "streamCount"
      | "streams"
      | "topUpStream"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "StreamCancelled"
      | "StreamClaimed"
      | "StreamCompleted"
      | "StreamCreated"
      | "StreamPaused"
      | "StreamResumed"
      | "StreamToppedUp"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelStream",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "claim", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "createScheduledStream",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createStream",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feeCollector",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimableAmount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecipientStreams",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSenderStreams",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStream",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStreamProgress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pauseStream",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recipientStreams",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resumeStream",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "senderStreams",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeCollector",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "streamCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "streams", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "topUpStream",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createScheduledStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecipientStreams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSenderStreams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStream", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getStreamProgress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pauseStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recipientStreams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resumeStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "senderStreams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "streamCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "streams", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "topUpStream",
    data: BytesLike
  ): Result;
}

export namespace StreamCancelledEvent {
  export type InputTuple = [
    id: BytesLike,
    senderRefund: BigNumberish,
    recipientPayment: BigNumberish
  ];
  export type OutputTuple = [
    id: string,
    senderRefund: bigint,
    recipientPayment: bigint
  ];
  export interface OutputObject {
    id: string;
    senderRefund: bigint;
    recipientPayment: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamClaimedEvent {
  export type InputTuple = [
    id: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [id: string, recipient: string, amount: bigint];
  export interface OutputObject {
    id: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamCompletedEvent {
  export type InputTuple = [id: BytesLike, totalClaimed: BigNumberish];
  export type OutputTuple = [id: string, totalClaimed: bigint];
  export interface OutputObject {
    id: string;
    totalClaimed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamCreatedEvent {
  export type InputTuple = [
    id: BytesLike,
    sender: AddressLike,
    recipient: AddressLike,
    totalAmount: BigNumberish,
    ratePerSecond: BigNumberish,
    startTime: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    id: string,
    sender: string,
    recipient: string,
    totalAmount: bigint,
    ratePerSecond: bigint,
    startTime: bigint,
    endTime: bigint
  ];
  export interface OutputObject {
    id: string;
    sender: string;
    recipient: string;
    totalAmount: bigint;
    ratePerSecond: bigint;
    startTime: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamPausedEvent {
  export type InputTuple = [id: BytesLike, pausedAt: BigNumberish];
  export type OutputTuple = [id: string, pausedAt: bigint];
  export interface OutputObject {
    id: string;
    pausedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamResumedEvent {
  export type InputTuple = [
    id: BytesLike,
    resumedAt: BigNumberish,
    newEndTime: BigNumberish
  ];
  export type OutputTuple = [id: string, resumedAt: bigint, newEndTime: bigint];
  export interface OutputObject {
    id: string;
    resumedAt: bigint;
    newEndTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamToppedUpEvent {
  export type InputTuple = [
    id: BytesLike,
    addedAmount: BigNumberish,
    newEndTime: BigNumberish
  ];
  export type OutputTuple = [
    id: string,
    addedAmount: bigint,
    newEndTime: bigint
  ];
  export interface OutputObject {
    id: string;
    addedAmount: bigint;
    newEndTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArcPayStreamPayment extends BaseContract {
  connect(runner?: ContractRunner | null): ArcPayStreamPayment;
  waitForDeployment(): Promise<this>;

  interface: ArcPayStreamPaymentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelStream: TypedContractMethod<
    [streamId: BytesLike],
    [void],
    "nonpayable"
  >;

  claim: TypedContractMethod<[streamId: BytesLike], [bigint], "nonpayable">;

  createScheduledStream: TypedContractMethod<
    [
      recipient: AddressLike,
      totalAmount: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish
    ],
    [string],
    "payable"
  >;

  createStream: TypedContractMethod<
    [recipient: AddressLike, totalAmount: BigNumberish, duration: BigNumberish],
    [string],
    "payable"
  >;

  feeCollector: TypedContractMethod<[], [string], "view">;

  getClaimableAmount: TypedContractMethod<
    [streamId: BytesLike],
    [bigint],
    "view"
  >;

  getRecipientStreams: TypedContractMethod<
    [recipient: AddressLike],
    [string[]],
    "view"
  >;

  getSenderStreams: TypedContractMethod<
    [sender: AddressLike],
    [string[]],
    "view"
  >;

  getStream: TypedContractMethod<
    [streamId: BytesLike],
    [ArcPayStreamPayment.StreamStructOutput],
    "view"
  >;

  getStreamProgress: TypedContractMethod<
    [streamId: BytesLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        totalAmount: bigint;
        claimedAmount: bigint;
        claimableAmount: bigint;
        remainingAmount: bigint;
        percentComplete: bigint;
      }
    ],
    "view"
  >;

  pauseStream: TypedContractMethod<[streamId: BytesLike], [void], "nonpayable">;

  protocolFee: TypedContractMethod<[], [bigint], "view">;

  recipientStreams: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  resumeStream: TypedContractMethod<
    [streamId: BytesLike],
    [void],
    "nonpayable"
  >;

  senderStreams: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  setFeeCollector: TypedContractMethod<
    [_feeCollector: AddressLike],
    [void],
    "nonpayable"
  >;

  setProtocolFee: TypedContractMethod<
    [_protocolFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  streamCount: TypedContractMethod<[], [bigint], "view">;

  streams: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: string;
        sender: string;
        recipient: string;
        totalAmount: bigint;
        claimedAmount: bigint;
        ratePerSecond: bigint;
        startTime: bigint;
        endTime: bigint;
        pausedAt: bigint;
        pausedDuration: bigint;
        state: bigint;
      }
    ],
    "view"
  >;

  topUpStream: TypedContractMethod<[streamId: BytesLike], [void], "payable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelStream"
  ): TypedContractMethod<[streamId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[streamId: BytesLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "createScheduledStream"
  ): TypedContractMethod<
    [
      recipient: AddressLike,
      totalAmount: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createStream"
  ): TypedContractMethod<
    [recipient: AddressLike, totalAmount: BigNumberish, duration: BigNumberish],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "feeCollector"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getClaimableAmount"
  ): TypedContractMethod<[streamId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRecipientStreams"
  ): TypedContractMethod<[recipient: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getSenderStreams"
  ): TypedContractMethod<[sender: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getStream"
  ): TypedContractMethod<
    [streamId: BytesLike],
    [ArcPayStreamPayment.StreamStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStreamProgress"
  ): TypedContractMethod<
    [streamId: BytesLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        totalAmount: bigint;
        claimedAmount: bigint;
        claimableAmount: bigint;
        remainingAmount: bigint;
        percentComplete: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pauseStream"
  ): TypedContractMethod<[streamId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "protocolFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recipientStreams"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "resumeStream"
  ): TypedContractMethod<[streamId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "senderStreams"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "setFeeCollector"
  ): TypedContractMethod<[_feeCollector: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setProtocolFee"
  ): TypedContractMethod<[_protocolFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "streamCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "streams"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: string;
        sender: string;
        recipient: string;
        totalAmount: bigint;
        claimedAmount: bigint;
        ratePerSecond: bigint;
        startTime: bigint;
        endTime: bigint;
        pausedAt: bigint;
        pausedDuration: bigint;
        state: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "topUpStream"
  ): TypedContractMethod<[streamId: BytesLike], [void], "payable">;

  getEvent(
    key: "StreamCancelled"
  ): TypedContractEvent<
    StreamCancelledEvent.InputTuple,
    StreamCancelledEvent.OutputTuple,
    StreamCancelledEvent.OutputObject
  >;
  getEvent(
    key: "StreamClaimed"
  ): TypedContractEvent<
    StreamClaimedEvent.InputTuple,
    StreamClaimedEvent.OutputTuple,
    StreamClaimedEvent.OutputObject
  >;
  getEvent(
    key: "StreamCompleted"
  ): TypedContractEvent<
    StreamCompletedEvent.InputTuple,
    StreamCompletedEvent.OutputTuple,
    StreamCompletedEvent.OutputObject
  >;
  getEvent(
    key: "StreamCreated"
  ): TypedContractEvent<
    StreamCreatedEvent.InputTuple,
    StreamCreatedEvent.OutputTuple,
    StreamCreatedEvent.OutputObject
  >;
  getEvent(
    key: "StreamPaused"
  ): TypedContractEvent<
    StreamPausedEvent.InputTuple,
    StreamPausedEvent.OutputTuple,
    StreamPausedEvent.OutputObject
  >;
  getEvent(
    key: "StreamResumed"
  ): TypedContractEvent<
    StreamResumedEvent.InputTuple,
    StreamResumedEvent.OutputTuple,
    StreamResumedEvent.OutputObject
  >;
  getEvent(
    key: "StreamToppedUp"
  ): TypedContractEvent<
    StreamToppedUpEvent.InputTuple,
    StreamToppedUpEvent.OutputTuple,
    StreamToppedUpEvent.OutputObject
  >;

  filters: {
    "StreamCancelled(bytes32,uint256,uint256)": TypedContractEvent<
      StreamCancelledEvent.InputTuple,
      StreamCancelledEvent.OutputTuple,
      StreamCancelledEvent.OutputObject
    >;
    StreamCancelled: TypedContractEvent<
      StreamCancelledEvent.InputTuple,
      StreamCancelledEvent.OutputTuple,
      StreamCancelledEvent.OutputObject
    >;

    "StreamClaimed(bytes32,address,uint256)": TypedContractEvent<
      StreamClaimedEvent.InputTuple,
      StreamClaimedEvent.OutputTuple,
      StreamClaimedEvent.OutputObject
    >;
    StreamClaimed: TypedContractEvent<
      StreamClaimedEvent.InputTuple,
      StreamClaimedEvent.OutputTuple,
      StreamClaimedEvent.OutputObject
    >;

    "StreamCompleted(bytes32,uint256)": TypedContractEvent<
      StreamCompletedEvent.InputTuple,
      StreamCompletedEvent.OutputTuple,
      StreamCompletedEvent.OutputObject
    >;
    StreamCompleted: TypedContractEvent<
      StreamCompletedEvent.InputTuple,
      StreamCompletedEvent.OutputTuple,
      StreamCompletedEvent.OutputObject
    >;

    "StreamCreated(bytes32,address,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      StreamCreatedEvent.InputTuple,
      StreamCreatedEvent.OutputTuple,
      StreamCreatedEvent.OutputObject
    >;
    StreamCreated: TypedContractEvent<
      StreamCreatedEvent.InputTuple,
      StreamCreatedEvent.OutputTuple,
      StreamCreatedEvent.OutputObject
    >;

    "StreamPaused(bytes32,uint256)": TypedContractEvent<
      StreamPausedEvent.InputTuple,
      StreamPausedEvent.OutputTuple,
      StreamPausedEvent.OutputObject
    >;
    StreamPaused: TypedContractEvent<
      StreamPausedEvent.InputTuple,
      StreamPausedEvent.OutputTuple,
      StreamPausedEvent.OutputObject
    >;

    "StreamResumed(bytes32,uint256,uint256)": TypedContractEvent<
      StreamResumedEvent.InputTuple,
      StreamResumedEvent.OutputTuple,
      StreamResumedEvent.OutputObject
    >;
    StreamResumed: TypedContractEvent<
      StreamResumedEvent.InputTuple,
      StreamResumedEvent.OutputTuple,
      StreamResumedEvent.OutputObject
    >;

    "StreamToppedUp(bytes32,uint256,uint256)": TypedContractEvent<
      StreamToppedUpEvent.InputTuple,
      StreamToppedUpEvent.OutputTuple,
      StreamToppedUpEvent.OutputObject
    >;
    StreamToppedUp: TypedContractEvent<
      StreamToppedUpEvent.InputTuple,
      StreamToppedUpEvent.OutputTuple,
      StreamToppedUpEvent.OutputObject
    >;
  };
}
